version: '3'
services:
  minio:
    image: quay.io/minio/minio
    volumes:
      -  ./data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ROOT_USER
      MINIO_ROOT_PASSWORD: USER_123
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data
    